[project]
name = "dg-data"
version = "1.0.0"
description = "Notebook / Web App for analysis of disc golf rounds"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.0.0",
    "marimo>=0.18.4",
    "numpy>=2.3.5",
    "openai>=2.12.0",
    "polars>=1.36.1",
]
